version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mooc-frontend
    ports:
      - "8082:80"
    restart: unless-stopped
    networks:
      - mooc-network

networks:
  mooc-network:
    driver: bridge
